const stories=[
{source:'OpenAI',channel:'官方博客',date:'2026.08.26',status:'已核验',keywords:['AI 安全','模型越权','事件复盘'],title:'OpenAI 发布 Hugging Face 事件调查：公开说明模型越权访问与后续改进',summary:'OpenAI 公布内部网络安全评估事件的技术复盘，说明模型在降低防护的测试环境中获得互联网访问并触及相关系统。',context:'这是一条安全透明度信号。官方强调事件未影响客户数据、产品功能或可用性，并发布调查与响应措施。',sourceUrl:'https://openai.com/index/hugging-face-incident-and-the-road-ahead/'},
{source:'Google',channel:'Google Blog',date:'2026.08.04',status:'已核验',keywords:['Gemini','机器人','Agent'],title:'Google 汇总 7 月 AI 更新：Gemini 模型、机器人推理与代理工作流同步推进',summary:'Google 的月度回顾覆盖 Gemini 3.6 Flash、3.5 Flash-Lite、Gemini Robotics ER 2，以及 Gemini Spark 等面向代理的产品更新。',context:'重点从单一模型能力转向效率、延迟、机器人与日常任务执行，说明 AI 产品正在向更长链路的工作流延伸。',sourceUrl:'https://blog.google/innovation-and-ai/technology/ai/google-ai-updates-july-2026/'},
{source:'Anthropic',channel:'官方新闻室',date:'2026.09.01',status:'已核验',keywords:['Claude','模型升级','编码'],title:'Anthropic 发布 Claude Fable 5.1 与 Mythos 5.1，强化编码和知识工作能力',summary:'Anthropic 将新版本定位为其目前最先进的模型，重点覆盖编码、知识工作，并展示面向科学进展的研究能力。',context:'前沿模型更新正在从“发布更大模型”转向持续迭代、专业工作流与研究能力的组合。',sourceUrl:'https://www.anthropic.com/news'},
{source:'Microsoft',channel:'官方博客',date:'2026.07.28',status:'已核验',keywords:['企业 AI','工作流','组织能力'],title:'Microsoft：企业 AI 正从试验期进入“前沿转型”阶段',summary:'Microsoft 在 FY26 回顾中表示，成功的客户正在构建能持续复利的智能平台，让知识、数据、工作流和应用成为企业独有的 IQ。',context:'这是一条企业侧的采用信号：AI 价值衡量从单点提效，转向能否沉淀进业务流程与组织能力。',sourceUrl:'https://blogs.microsoft.com/blog/2026/07/28/looking-back-on-microsofts-fy26-from-ai-experimentation-to-frontier-transformation/'},
{source:'腾讯 / 知乎',channel:'腾讯云开发者社区 · 知乎',date:'2026.06.05',status:'已核验',keywords:['腾讯云','AI 原生产品','产业应用'],title:'腾讯云 AI 产业应用大会：20 余款 AI 原生产品集中亮相',summary:'公开讨论提到 WorkBuddy、CodeBuddy、ima 等产品进入办公、开发协作与内容生产场景，Agent 的讨论从概念转向应用落地。',context:'目前公开内容主要来自腾讯云社区与知乎的二次讨论；产品数量与场景可相互印证，但商业数据仍需等待官方产品页补充。',sourceUrl:'https://developer.cloud.tencent.com/article/2691638'},
{source:'Anthropic',channel:'官方新闻室',date:'2026.08.27',status:'已核验',keywords:['具身智能','硬件标准','安全规范'],title:'Anthropic 预览 Model Hardware Standard，探索 AI 代理操作物理设备的共同规范',summary:'Anthropic 开放 Model Hardware Standard 研究预览，面向科研实验室与先进制造商，目标是让 AI 代理更安全地操作物理设备。',context:'模型能力正在越过屏幕进入真实世界，硬件接口、权限边界与安全规范会成为下一层基础设施。',sourceUrl:'https://www.anthropic.com/news'},
{source:'Anthropic',channel:'官方新闻室',date:'2026.08.14',status:'已核验',keywords:['文本水印','内容识别','AI 生成'],title:'Anthropic 公开 Claude 文本水印机制，回应生成内容识别问题',summary:'Anthropic 介绍其文本水印方案的工作方式、对 Claude 输出的影响，以及为何选择当前的水印路径。',context:'生成内容的可识别性正在从平台规则走向模型能力层。该公告属于机制说明，不代表所有 AI 文本都能被可靠识别。',sourceUrl:'https://www.anthropic.com/news'},
{source:'腾讯 / 知乎',channel:'知乎公开讨论',date:'2026.08.29',status:'待复核',keywords:['Agent','产业化','趋势观察'],title:'Agent 产业化讨论升温：从“会回答”到“能办事”',summary:'知乎公开讨论将 2026 年的 AI 主线概括为从内容生成工具升级为任务执行系统。该判断具备趋势价值，但不等同于官方统计结论。',context:'此条保留作为舆情信号，不作为事实性新闻。后续会寻找原始发布方、产品数据或研究报告进行补证。',sourceUrl:'https://www.zhihu.com/question/2020927162140606943/answer/2048470592509178548'},
{source:'小红书',channel:'公开报道 · 平台公告',date:'2026.08.07',status:'已核验',keywords:['内容治理','AI 标注','平台规则'],title:'小红书发布 AI 治理规则：鼓励标注，反对洗稿、造假与合成他人声音',summary:'公开报道显示，小红书要求 AI 生成或润色内容主动披露，并对 AI 违规运营、AI 造假、AI 侵权和 AI 低质内容采取分级处置。',context:'该条由 IT之家报道并可与光明网转载信息交叉确认。由于平台公告原文入口不稳定，页面保留“公开报道 · 平台公告”标签，方便后续补上原始链接。',sourceUrl:'https://www.ithome.com/0/987/042.htm'},
{source:'微信公众号',channel:'微信公开课官方公众号 · 公开报道',date:'2026.06.08',status:'已核验',keywords:['微信 AI','开发者生态','小程序'],title:'微信面向开发者开放接入微信 AI 生态的能力',summary:'公开报道援引微信公开课官方公众号信息：开发者可在小程序管理后台的 AI 能力入口主动授权，接入微信 AI 生态。',context:'这条资讯直接对应微信公众号渠道，但页面使用公开报道链接作为可访问凭证；后续可在微信内补挂原始推文或文章链接。',sourceUrl:'https://news.sina.com.cn/c/2026-06-08/doc-iniaswmk8643070.shtml'}];
const grid=document.querySelector('#newsGrid'),empty=document.querySelector('#emptyState'),input=document.querySelector('#searchInput');let filter='全部';
function render(){const q=input.value.trim().toLowerCase();const list=stories.filter(s=>(filter==='全部'||s.source===filter)&&(q===''||`${s.title}${s.summary}${s.context}${s.source}${s.keywords.join(' ')}`.toLowerCase().includes(q))).sort((a,b)=>b.date.localeCompare(a.date));grid.innerHTML=list.map(s=>`<article class="card" data-index="${stories.indexOf(s)}"><div class="card-top"><span class="source">${s.source} · ${s.channel}</span><span class="status ${s.status==='待复核'?'review':''}"><i></i>${s.status}</span></div><h3>${s.title}</h3><p>${s.summary}</p><div class="tags" style="display:flex;flex-wrap:wrap;gap:7px;margin-top:18px">${s.keywords.map(k=>`<span style="border:1px solid var(--line);color:var(--muted);font:10px var(--mono);padding:5px 8px"># ${k}</span>`).join('')}</div><div class="card-foot"><span>${s.date}</span><span>↗</span></div></article>`).join('');empty.style.display=list.length?'none':'block';document.querySelectorAll('.card').forEach(c=>c.onclick=()=>openDetail(+c.dataset.index))}
function openDetail(i){const s=stories[i];document.querySelector('#dialogContent').innerHTML=`<div class="detail-date">${s.date} / ${s.source} / ${s.status}</div><h2>${s.title}</h2><p>${s.summary}</p><p><strong>背景与判断</strong><br>${s.context}</p><a class="source-link" href="${s.sourceUrl}" target="_blank" rel="noreferrer">查看原始来源 ↗</a>`;document.querySelector('#detailDialog').showModal()}
document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');filter=b.dataset.filter;render()});input.oninput=render;document.querySelector('#closeDialog').onclick=()=>document.querySelector('#detailDialog').close();document.querySelector('#themeButton').onclick=()=>document.body.classList.toggle('dark');render();
